### ISSUE TITLE
[Bug] Crashes when project name is 'go'

### ISSUE THREAD

**Issue by MohitNishad** [Melkeydev/go-blueprint#261]
### What is the problem?

When i was trying to initialize my project with the name 'go' i get this error. 
![image](https://github.com/Melkeydev/go-blueprint/assets/121090745/a2177288-b95a-4260-bb63-dbce5a79694d)
 

### Operating System

Linux mint MATE 1.26.0

### Architecture Version (x86, x64, arm, etc)

x64

### Steps to reproduce

When i create a project with any name it should create. 
![image](https://github.com/Melkeydev/go-blueprint/assets/121090745/f3397e01-7936-4bbc-92b2-6784c14da1ff)

### Relevant log output

```shell
..
 Next steps:
 • cd into the newly created project with: `cd proj`
                                                    
 Tip: Repeat the equivalent Blueprint with the following non-interactive command:
 • go-blueprint create --name proj --framework fiber --driver mongo --advanced false
```

**Comment by Ujstor** [comment]
This is a feature, not a bug.

Check what you get with go mod init if you try to name it go:

```bash
go mod init go
go: creating new go.mod: module go
panic: go: internal error: missing go root module

goroutine 1 [running]:
cmd/go/internal/modload.mustHaveGoRoot(...)
        cmd/go/internal/modload/buildlist.go:104
cmd/go/internal/modload.newRequirements(0x60?, {0xc00018a1e0?, 0x9c5f60?, 0xc0000100d8?}, 0x2aaaaaaaa?)
        cmd/go/internal/modload/buildlist.go:118 +0x6f8
cmd/go/internal/modload.updatePrunedRoots({0xba6df0, 0xf8d080}, 0xc0001bfd40, 0xc0001e4050, {0x0, 0x0, 0x1?}, {0x0, 0x0, 0x0}, ...)
        cmd/go/internal/modload/buildlist.go:1236 +0xb70
cmd/go/internal/modload.updateRoots({0xba6df0?, 0xf8d080?}, 0xb9ea0a?, 0x6?, {0x0?, 0x1?, 0xa927a6?}, {0x0, 0x0, 0x0}, ...)
        cmd/go/internal/modload/buildlist.go:796 +0x9d
cmd/go/internal/modload.CreateModFile({0xba6df0, 0xf8d080}, {0x7ffd0db7e540, 0x2})
        cmd/go/internal/modload/init.go:1058 +0x825
cmd/go/internal/modcmd.runInit({0xba6df0?, 0xf8d080?}, 0xc000026660?, {0xc0000e4070?, 0x9cef40?, 0x19?})
        cmd/go/internal/modcmd/init.go:48 +0x8c
main.invoke(0xf1ea20, {0xc0000e4060, 0x2, 0x2})
        cmd/go/main.go:257 +0x5c4
main.main()
        cmd/go/main.go:175 +0x6d5
```
