### ISSUE TITLE
[Bug] Panic occurs when there is no git

### ISSUE THREAD

**Issue by muhi111** [Melkeydev/go-blueprint#360]
### What is the problem?

Without git installed, running `go-blueprint create --name app --framework echo --driver postgres --git skip` causes panic. CreateMainFile() at cmd/createate.go:271 returns an error and goes into error handling, but at line 273 ReleaseTerminal() panics (is it bad that p.cancelReader is nil?), and even after recovering, it still panics. The same thing seems to be happening again even after further recovering.

I could not reproduce the same bug on my Ubuntu 22.04 (x86-64). I am not very familiar with go, so please feel free to point out if I am saying something strange.🙇

### Operating System

Amazon Linux 2

### Architecture Version (x86, x64, arm, etc)

x86_64

### Steps to reproduce

1. With git not installed, run `go-blueprint create --name app --framework echo --driver postgres --git skip`

### Relevant log output

```shell
The program encountered an unexpected issue and had to exit. The error was: runtime error: invalid memory address or nil pointer dereference
If you continue to experience this issue, please post a message on our GitHub page or join our Discord server for support.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x57fa0c]

goroutine 1 [running]:
github.com/charmbracelet/bubbletea.(*Program).ReleaseTerminal(0xc000188240)
        /home/ec2-user/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:611 +0x2c
github.com/melkeydev/go-blueprint/cmd.init.func1.2()
        /home/ec2-user/go-blueprint/cmd/create.go:264 +0xbd
panic({0x638960?, 0x8ae220?})
        /usr/local/go/src/runtime/panic.go:785 +0x132
github.com/charmbracelet/bubbletea.(*Program).ReleaseTerminal(0xc000188240)
        /home/ec2-user/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:611 +0x2c
github.com/melkeydev/go-blueprint/cmd.init.func1(0x8b6180, {0xc000148180?, 0x0?, 0x8?})
        /home/ec2-user/go-blueprint/cmd/create.go:273 +0x1f0b
github.com/spf13/cobra.(*Command).execute(0x8b6180, {0xc000148100, 0x8, 0x8})
        /home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x8b6460)
        /home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ec2-user/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/melkeydev/go-blueprint/cmd.Execute()
        /home/ec2-user/go-blueprint/cmd/root.go:20 +0x1a
main.main()
        /home/ec2-user/go-blueprint/main.go:6 +0xf
exit status 2
```

**Comment by Ujstor** [comment]
Bug is not critical because most of the users have Git installed, but it would be good to fix this in the near future.

**Comment by Ujstor** [comment]
PR merged.
